### ISSUE TITLE
ECFP fingerprint computation

### ISSUE THREAD

**Issue by sabrina-rashid** [dmis-lab/ReSimNet#1]
How are you computing ECFP fingerprints? I am using the following command to compute fingerprint for the first compound in the AABA.csv file. But it does not seem to match with what you have in that file. Any help would be much appreciated.

from rdkit import Chem
mol = Chem.MolFromSmiles("Cn1cc([N+](=O)[O-])c(=O)n(C)c1=O")
fp = Chem.RDKFingerprint(mol)
a = fp.ToBitString()

Thanks,

**Comment by mjjeon** [comment]
> How are you computing ECFP fingerprints? I am using the following command to compute fingerprint for the first compound in the AABA.csv file. But it does not seem to match with what you have in that file. Any help would be much appreciated.
> 
> from rdkit import Chem
> mol = Chem.MolFromSmiles("Cn1cc([N+](=O)[O-])c(=O)n(C)c1=O")
> fp = Chem.RDKFingerprint(mol)
> a = fp.ToBitString()
> 
> Thanks,

Hi, 
I used the following codes to get ECFP fingerprints. Hope it is helpful. 

mol = Chem.MolFromSmiles(smilesstr)
fp_obj = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048, useChirality=True)
arr = np.zeros((1,))
DataStructs.ConvertToNumpyArray(fp_obj, arr)

If you have further questions, please let me know.
Thanks,
